### ISSUE TITLE
not cracked!

### ISSUE THREAD

**Issue by NotVerble** [FinalException/Adjust#1]
Please help man it has been longer than 30 mins and our lord and saviour Johnathan Hardwick has not cracked Adjust!

**Comment by FinalException** [comment]
that is a problem that can't be solved unfortunately. sadly, jonathan only knows how to ctrl + v on Nivia source

**Comment by NotVerble** [comment]
Awww, that sucks. Maybe our god will be able to do this someday, until then you are a dirty liar.
